development:
  access_key_id: AKIAIYUPPZFRGDMBAL2A
  secret_access_key: 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 
  bucket: julienwat75



  test:
  access_key_id: AKIAIYUPPZFRGDMBAL2A
  secret_access_key: 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 
  bucket: julienwat75

  production:
  access_key_id: AKIAIYUPPZFRGDMBAL2A
  secret_access_key: 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 
  bucket: julienwat75

  
